import {
    CLIENT_ID,
    PROJECT_ID,
    AUTH_URI,
    TOKEN_URI,
    AUTH_PROVIDER_x509_CERT_URL,
    CLIENT_SECRET,
    REDIRECT_URIS,
    CLIENT_SCOPES,
    RESPONSE_TYPE
} from './googleAuth';

export  {
    CLIENT_ID,
    PROJECT_ID,
    AUTH_URI,
    TOKEN_URI,
    AUTH_PROVIDER_x509_CERT_URL,
    CLIENT_SECRET,
    REDIRECT_URIS,
    CLIENT_SCOPES,
    RESPONSE_TYPE
}